version: '2'
services:

  db:
    container_name: odoo_10_db
    image: postgres:10
    ports:
      - "8510:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    restart: always

  web:
    container_name: odoo_10_web
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "28069:8069"
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - web-data:/var/lib/odoo  
    restart: always

volumes:
  db-data:
  web-data:
